{% set name = "lunchable" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lunchable-{{ version }}.tar.gz
  sha256: abfe22d884de5780e15449bbdf4ccdb9c615ea78c05403a79f991ad9aeeb0882

build:
  entry_points:
    - lunchable = lunchable._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0
    - click >=8.0.1
    - pydantic >=2,<3
    - rich >=10.0.0
    - httpx
    - importlib-metadata >=3.6
    - click-plugins >=1.1.1

test:
  imports:
    - lunchable
  commands:
    - pip check
    - lunchable --help
  requires:
    - pip

about:
  summary: A simple Python SDK around the Lunch Money Developer API
  dev_url: https://github.com/juftin/lunchable
  license: MIT
  license_file: LICENSE
  home: https://github.com/juftin/lunchable

extra:
  recipe-maintainers:
    - juftin
