{% set name = "lunchable" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lunchable-{{ version }}.tar.gz
  sha256: 997d13b3a196f89f99a6d434c636226bede3e8625e71d77ed379cce580262ccf

build:
  entry_points:
    - lunchable = lunchable._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - click >=8.0.1
    - pydantic >=2,<3
    - rich >=10.0.0
    - httpx
    - importlib-metadata >=3.6
    - click-plugins >=1.1.1

test:
  imports:
    - lunchable
  commands:
    - pip check
    - lunchable --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A simple Python SDK around the Lunch Money Developer API
  dev_url: https://github.com/juftin/lunchable
  license: MIT
  license_file: LICENSE
  home: https://github.com/juftin/lunchable

extra:
  recipe-maintainers:
    - juftin
